# zshenv -> [login? zprofile] -> [interactive? zshrc] -> [login? zlogin] -> [exiting? zlogout]
# After the zlogin scripts are read, if the shell is interactive, commands are read from /etc/zshrc and then $ZDOTDIR/.zshrc
# An interactive shell reads commands from user input on a tty (a non-script). A shell run as a script is a non-interactive shell
$DOTFILES_NOISY_STARTUP && echo "== Running $HOME/.zshrc"

source $ZPREZTODIR/runcoms/zshrc

# bootstrap dotfiles
. $DOTDIR/modules/dotfiles/dotfiles.zsh
. $DOTDIR/modules/zsh/functions/autoload-fpath
autoload-fpath $DOTDIR/modules/zsh/functions

# bring in the prompts
autoload-fpath $DOTDIR/local/prompts

# for bash completion scripts
autoload bashcompinit
bashcompinit

# load zgen
source "${DOTDIR}/local/boot/save_aliases.zsh"
source "${HOME}/.zgen/zgen.zsh"
source "${DOTDIR}/local/boot/restore_aliases.zsh"

# While developing:
#dotfiles-reset-cache

# jump to local module which will init the rest of the dotfiles/modules
source $DOTDIR/local/boot/init.zsh
