echo ZSH/ZSHENV

# the basics
#: ${HOME=~}                                 # should always be set anyway
#: ${LOGNAME=$(id -un)}                      # should also be set by environment

export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LANGUAGE=en

# Identity
export EMAIL="ian@ianduggan.net"
export FULLNAME="Ian Duggan"

# IRC
export IRCNICK=ijcd
export IRCNAME=${FULLNAME}

# Debian
export DEBEMAIL=$EMAIL
export DEBFULLNAME=$FULLNAME

# Git
export GIT_AUTHOR_NAME=$FULLNAME
export GIT_COMMITTER_NAME=$FULLNAME
export GIT_AUTHOR_EMAIL=$EMAIL
export GIT_COMMITTER_EMAIL=$EMAIL

# Prevent ZSH from stating all of Maildir
export MAILCHECK=0

# Rsync stuff
export RSYNC_RSH=ssh

# Workflow Stuff
export INBOX=~/Desktop/Inbox
export OUTBOX=~/Desktop/Outbox
export PENDING=~/Desktop/Pending
export I=$INBOX
export O=$OUTBOX
export P=$PENDING
