call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-sensible'

" #Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }

" Plug 'scrooloose/syntastic'

" " surround
" Plug 'tpope/vim-surround'

" " fuzzy finder
" Plug 'kien/ctrlp.vim'

" " solarized colors
" Plug 'altercation/vim-colors-solarized'

" " better status bar
" Plug 'bling/vim-airline'

" " tag outliner
" Plug 'majutsushi/tagbar'

" " better commenter
" Plug 'scrooloose/nerdcommenter'

" " git stuff
" Plug 'tpope/vim-fugitive'
" Plug 'airblade/vim-gitgutter'

" " completion
" Plug 'valloric/youcompleteme'

" " quick movement
" Plug 'easymotion/vim-easymotion'

" " tab insert mode completions
" Plug 'ervandew/supertab'

" syntax
" Initialize plugin system
call plug#end()

if $VIM_CRONTAB == "true"
    set nobackup
    set nowritebackup
endif

nmap <F7> :NERDTreeToggle<CR>
nmap <F8> :TagbarToggle<CR>
